version: "3.8"
services:
  rails-api-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    volumes:
      - rails_storage:/rails/storage
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db-prod:5432/rails_api_production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    depends_on:
      - db-prod

  db-prod:
    image: postgres:15
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rails_api_production
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data_prod:
  rails_storage:
# To start the production environment, run:
# docker compose -f docker-compose-prod.yml up -d --build

# To start a migration, run:
# docker compose -f docker-compose-prod.yml exec rails-api-prod bundle exec rails db:migrate
